###

GET http://localhost:8000/api/user/

###

GET http://localhost:8000/api/user/6294fc84feefc780929937fd



###

POST http://localhost:8000/api/user/signin
Content-Type: application/json

{
    "email": "waldojavier.vo@gmail.com",
    "password": "pordouglas"
}

###

POST http://localhost:8000/api/user/logout

###

PUT http://localhost:8000/api/user/629455975313c69abac4c92e/budget
Content-Type: application/json

{
    "budget": "10000"
}

